### ISSUE TITLE
Missing make dependencies

### ISSUE THREAD

**Issue by avaldebe** [metno/uEMEP#4]
Hi @brucerd 

There are no rules for compiling `uEMEP_read_industry_data.f90` and `uEMEP_save_emission_netcdf.f90` and linking them into `uEMEPv3`.
I think you forgot to commit your last changes to `Makefile.SRCS` and `dependencies`...

I added the necessary changes to my local copy, but can not push as I'm not a collaborator on this repository.

Cheers,
Á.

**Comment by brucerd** [comment]
Hi Alvaro, You are right.  Fix when I get back. Bruce
