### ISSUE TITLE
ERROR: Found zero wind fields in both components

### ISSUE THREAD

**Issue by avaldebe** [metno/uEMEP#7]
Hi Bruce,

I'm testing with the tiling of 18UTC run for 20190902 and get the following error message.

```text
================================================================
Reading EMEP data (uEMEP_read_EMEP)
================================================================
[...]
ero wind fields at (i,j,t):           19          19           1
Wind not found for (loop,i,j,t):           20          19          19           1      0.00      0.00
ERROR: Found zero wind fields in both components (i,j,t). Stopping:            1           1           1
```

I'm using the update 5 configuration file `uEMEP_EMEP4NO_config_hourly_default_PPI_update_5.txt`, with the following additional config for 18UTC:

```FORTRAN
file_tag='Norway'
forecast_hour_str='18'
filename_EMEP(1)='CWF_<replace_hour>AQNO-<yyyymmdd>_hour.nc'
filename_EMEP(2)='CWF_<replace_hour>AQNO-<yyyymmdd>_uEMEP_hour.nc'
filename_EMEP(3)='meps_mbr0_extracted_2_5km_<yyyymmdd>T<replace_hour>Z.nc'
pathname_rl(2)='/lustre/storeB/project/fou/kl/emep/ModelRuns/NORTRIP/Forecast_2019/NORTRIP_out/emissions/'
filename_rl(2)='uEMEP_emissions_all_sand_salt_<replace_date>.txt'
pathname_emissions_for_EMEP='/lustre/storeB/project/fou/kl/emep/ModelRuns/EMEP4NO/uEMEP_emissions_for_EMEP_v3/'
! Meteo files have 66 records, but we can use only 65
start_time_meteo_nc_index=2
end_time_meteo_nc_index=67
start_time_nc_index=1
end_time_nc_index=66
save_emissions_start_index=1
save_emissions_end_index=66
```

Can you help me out?

**EDIT** Do not know if it is relevant, but the output from the 20190902 18UTC starts 6h later, on 20190903 00UTC.

**Comment by brucerd** [comment]
OK,
First the tiles do not nead the meteo time index, they read meteo from EMEP, same with emissions you don't need these time index either, or the pathname to the emissions or filename_EMEP(3). I would need to see the rest of the log to see what it is reading. I put this trap in here before because there was a problem with EMEP4NO. Have you checked it is correct? 

Is EMEP4NO starting at 18 or is it 19? If it is at 18 then you need to use
start_time_nc_index=2
If it is 54 hours long then you need
end_time_nc_index=54

As I said in the dark without all the log.

Bruce

**Comment by avaldebe** [comment]
> Is EMEP4NO starting at 18 or is it 19? If it is at 18 then you need to use
> start_time_nc_index=2
> If it is 54 hours long then you need
> end_time_nc_index=54

EMEP4NO starts at 18, but output starts at 18+6

**Comment by avaldebe** [comment]
Changing the `end_time_nc_index` as you recommended worked.

```diff
 start_time_meteo_nc_index=2
 end_time_meteo_nc_index=67
 start_time_nc_index=1
-end_time_nc_index=66
+end_time_nc_index=55
 save_emissions_start_index=1
 save_emissions_end_index=66
```

The only problem now is that the name of the tile files.
For tile 44 the output file is `uEMEP_Norway_40to5km_00044_2019090219_18.nc`
where it used to be `uEMEP_Norway_40to5km_00044_20190902_18.nc`,
but that is another issue.

**Comment by brucerd** [comment]
I guess this is closed now
