### ISSUE TITLE
uEMEP tile file name

### ISSUE THREAD

**Issue by avaldebe** [metno/uEMEP#8]
When running creating emissions on the latest EMEP4NO setup the files are named after the first time step on the file, e.g. for 20190901 18UTC the output file for tile 44 is
 `uEMEP_Norway_40to5km_00044_2019090219_18.nc` where it used to be `uEMEP_Norway_40to5km_00044_20190902_18.nc`

_Originally posted by @avaldebe in https://github.com/metno/uEMEP/issues/7#issuecomment-528274960_

Can you add a filename ending keyword? Something I can use like this:

```FORTRAN
filename_ending_tiles = "<yyyymmdd>_<replace_hour>"
```

This is pretty much like what I ask on #6, so maybe you can create a single keyword, e.g. `filename_ending_output`.

**Comment by brucerd** [comment]
Have implemented a new variable in the config file

	filename_date_output_grid='<yyyymmdd>_<replace_hour>'

this is valid for all outputs, also station output which uses the same routines.

Have pushed the new code

**Comment by avaldebe** [comment]
That seems to work, should also close #6
